# Generated by Django 3.1.7 on 2021-04-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_text',
            field=models.CharField(max_length=500, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_text',
            field=models.CharField(max_length=50, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname_text',
            field=models.CharField(max_length=50, verbose_name='昵称'),
        ),
    ]
